README.md
examples/api_trait_implementation.rs
examples/reply_to_message_updates.rs
src/api_impl.rs
src/api_params.rs
src/objects.rs

partially fixes #10. The two types user_id and chat_id which need 64bit types are fixed. But there still is a lot of isize.
Please check for mistakes in here. Tests are green and it builds but that's not everything.
This changed to following types:
- ChatIdEnum::IntegerVariant `i64`
- chat_id `i64`
- date `u64`
- message_id `i32`
- user_id `u64`
- update_id `u32`
- *width `u32`
- *height `u32`
- *size `u32`
- *duration `u32`
- *offset `u32`
- *limit `u32`
- *timeout `u32`
As this is a breaking change I suggest the next release could also include some suggestions from `cargo clippy --all-targets -- -W clippy::pedantic`.

refactor: move main properties away from isize

---

src/api.rs
src/api_params.rs
src/objects.rs

This changes all the 64bit integers to something smaller when not needed. Mostly 32bit, but some things are even smaller. For example `length`/`offset` in a 4096 text message with u32 is just way too big.
fixes #10

refactor: dont use 64bit integer when not needed

---

Cargo.toml
src/lib.rs

closes #29 
This also specifies that certain examples require the http-client feature.
As the `api_trait_implementation` example only requires serde_json
it is added as a dev-dependency.
Versions specified in Cargo.toml are using semver to install the latest.
Specifying 2.3 will install 2.6 which is counterintuitive.
Removing the minor version is more expressive about what is happening.
(Also the `Cargo.toml` is sorted by alphabet)
This is a breaking change but probably not worth its own release as `default-features = false` still works the same.

rename impl feature to http-client

---

src/api_impl.rs

Hey, thank you for this project! 
I couldn't find a way to add a timeout to the default http client, so I modified the existing code a bit. 
This was needed because sometimes my client just gets stuck forever waiting for a network response.
I also made the change to reuse the existing client instead of creating one each time, this helps speed up things on small boards (I'm using a Pi Zero W) and makes it so we don't need to reconfigure the timeout each time. 
Had to remove the PartialEq derive because the ureq agent doesn't implement it. 
Anyway, thank you for the great project and feel free to reject this change if it doesn't fit the project for any reason or should be implemented another way.

Add timeout option with default as 60s

---

Cargo.toml

I noticed the dependency graph was pretty heavy due to `multipart`, this helps the problem by disabling a bunch of unused features.

Reduce number of dependencies by disabling features from multipart

---

src/api_params.rs
src/lib.rs
src/objects.rs
src/parse_mode.rs

This prevents errors like using "Html" where "HTML" would have been required.
BREAKING CHANGE: string input for parse_mode isnt working anymore as the enum is required.

ParseMode enum

---

src/api_params.rs
src/objects.rs

`Copy` provides performance benefits over call-by-reference and `.clone()`

derive Copy when possible

---

Cargo.toml
src/api.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/api_traits.rs

`thiserror` implements `std::error::Error`. Having the std Error implemented is helpful for error handling as crates like `anyhow` or other errors like `std::io::Error` automatically work via `Into`.
also `parameters` was added to the `ErrorResponse` which could be helpful for the retry_after property.

Error handling

---

Cargo.toml
README.md
examples/api_trait_implementation.rs
examples/async_file_upload.rs
examples/async_reply_to_message_updates.rs
examples/reply_to_message_updates.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/api_params.rs
src/objects.rs

I tested this in one repo and it worked fine. As this touches basically everything it should be checked more carefully I guess.
closes #46
BREAKING CHANGES:
- FooBarBuilder::default() → FooBar::builder()
- build().unwrap() → build()

switch to typed-builder

---

src/api/telegram_api_impl.rs
src/api_params.rs
src/api_traits/async_telegram_api.rs
src/api_traits/telegram_api.rs
src/objects.rs

* Added the class ChatAdministratorRights and the methods
setMyDefaultAdministratorRights and getMyDefaultAdministratorRights
for managing the bot's default administrator rights.
* Added the field last_synchronization_error_date to the class
WebhookInfo.
* Renamed the field can_manage_voice_chats to can_manage_video_chats
in the class ChatMemberAdministrator. The old field will remain
temporarily available.
* Renamed the parameter can_manage_voice_chats to
can_manage_video_chats in the method promoteChatMember. The old
parameter will remain temporarily available.
* Renamed the fields voice_chat_scheduled, voice_chat_started,
voice_chat_ended, and voice_chat_participants_invited to
video_chat_scheduled, video_chat_started, video_chat_ended, and
video_chat_participants_invited in the class …

Bot api 6 changes without web apps changes

---

src/api_params.rs
src/api_traits/async_telegram_api.rs
src/api_traits/telegram_api.rs
src/objects.rs

- Added support for Web Apps, see the [detailed manual here](https://core.telegram.org/bots/webapps). ([blog announcement](https://telegram.org/blog/notifications-bots))
- Added the class [WebAppInfo](https://core.telegram.org/bots/api#webappinfo) and the fields web_app to the classes [KeyboardButton](https://core.telegram.org/bots/api#keyboardbutton) and [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton).
- Added the class [SentWebAppMessage](https://core.telegram.org/bots/api#sentwebappmessage) and the method [answerWebAppQuery](https://core.telegram.org/bots/api#answerwebappquery) for sending an answer to a Web App query, which originated from an inline button of the 'web_app' type.
- Added the class …

Bot API v6 web apps changes

---

src/objects.rs

the size of the `Message` struct changed from 5136 bytes to 672 bytes
```rust
mem::size_of::<frankenstein::Message>()
```
resolves https://github.com/ayrat555/frankenstein/issues/67 and https://github.com/ayrat555/frankenstein/issues/63

box struct fields in Message

---

src/api.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/objects.rs
src/parse_mode.rs

This is a breaking change but it improves efficiency or readability
- https://rust-lang.github.io/rust-clippy/master/index.html#vec_box
- https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
- https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref

refactor: adopt breaking lints

---

src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs

Increase the client timeout to 500s. The bot API itself also has 500 seconds of timeout (thats where the magic number 500 comes from).
The actual number is just copied over from this discussion in grammY, a Telegram Bot Library for Deno/Node.js: https://github.com/grammyjs/grammY/pull/79#discussion_r746618466
grammY uses the 500s timeout for 5 months now without any known issues.
Here are the official docs for it in grammY: https://doc.deno.land/https://deno.land/x/grammy@v1.9.2/mod.ts/~/ApiClientOptions#timeoutSeconds
Yes, I have seen the issue #74 and I am not sure if that's really something a default should handle. I don't want to repeat the discussion of the grammY PR I linked, it discussed a lot of specifics there.
The reason why I noticed it: My bot uploads multiple hundreds of MB …

Use client timeout of 500 seconds

---

examples/async_reply_to_message_updates.rs
examples/reply_to_message_updates.rs

This change moves `update_params` creation out of the case, when response is recognized as a message. If the response wasn't a message, the code might enter an infinite loop.

examples: fix cases when offset was not updated

---

src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs

#95 CI fails due to new lints. I fixed them and some minor improvements I saw nearby. Works exactly the same as before, just a bit more performance due to one less clone :innocent:

refactor(lint): adapt to lints

---

src/objects.rs

The proper status is 'kicked', not 'banned'. It was fixed in #78, but lost somehow.

Parse 'kicked' chat member status

---

src/objects.rs

Don't fail when unknown entity type is received. Fixed #145

Accept unknown message entity types

---

.github/workflows/rust.yml

Split up the Rust CI into multiple jobs running in parallel. This results in faster results as clips / test are no longer in sequence. Also, the feature set is not automatically tested via cargo-hack instead of some predefined list.

ci(rust): split clippy, features and test

---

src/objects.rs

https://core.telegram.org/bots/api#giveaway
```
winner_count 	Integer 	The number of users which are supposed to be selected as winners of the giveaway
```

fix: field name typo

---

src/objects.rs

Chat IDs can be negative, which causes response parsing to fail when the user selects a supergroup.

Use `i64` for `ChatShared::chat_id`

---

src/objects.rs

Fixes decoding error that happens decoding an update that contains ChatMemberRestricted.
#164

Remove "status" from ChatMemberRestricted

---

src/objects.rs

fixes https://github.com/ayrat555/frankenstein/issues/164#issuecomment-2078813442

fix: `message_id` is optional in `ExternalReplyInfo`

---

src/api_params.rs
src/api_traits/async_telegram_api.rs
src/api_traits/telegram_api.rs
src/objects.rs

https://core.telegram.org/bots/api#july-1-2024

Bot API 7.6

---

Cargo.toml
src/api_params.rs
src/objects.rs

Added the lint (which is why I noticed it) so it won't happen again in the future.
Also simplify some match cases I noticed.

feat: add Eq when possible on PartialEq

---

Cargo.toml
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/lib.rs
src/parse_mode.rs

Adding must_use is considered a breaking change.
While it is, I think it can be considered a bug when it isn't used before so I would be fine not releasing it as major version and consider it as a bug fix release.
Will create a conflict with #190, so I'll do this as a draft for now.

refactor: clippy::must_use_candidate

---

src/api_traits.rs

It's not yet on stable but errors the nightly clippy CI runs.
https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph

fix: clippy::too_long_first_doc_paragraph

---

examples/async_reply_to_message_updates.rs
examples/reply_to_message_updates.rs

As noticed on https://github.com/ayrat555/frankenstein/pull/196#discussion_r1740170364 this simplifies the examples to be closer to the actual intended logic of updating the offset on the existing `update_params`.

docs(examples): simplify update offset logic

---

examples/api_trait_implementation.rs
src/api.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs

Also, `From<std::io::Error> for Error` is removed as it could result in accidental wrong error kinds when the `?` operator is used.
BREAKING CHANGE: `Error::Http` changed and `HttpError` struct is gone.

refactor!: merge Error and HttpError

---

examples/api_trait_implementation.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/api_traits/async_telegram_api.rs
src/api_traits/telegram_api.rs

Generic names like T1 or T2 are quite useless to understand what their purpose / goal is. This is renaming them to something more speaking.
Also simplify some code in relation to generics and allow Rust to assume a bunch of them by itself.

refactor: improve generic argument naming

---

examples/async_reply_to_message_updates.rs
examples/reply_to_message_updates.rs
src/api.rs
src/api/async_telegram_api_impl.rs
src/api/telegram_api_impl.rs
src/json.rs
src/lib.rs

BREAKING CHANGE: `(Async)Api::encode_params` is gone
Its was likely meant for internal use only anyway

refactor(json)!: generalize encoding/decoding

---

src/lib.rs

see https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg
While other projects seem to `--cfg docsrs` in the Cargo.toml this is likely not required (anymore?) as its documented as the way to [detect docs.rs](https://docs.rs/about/builds#detecting-docsrs)
Can be locally previewed:
```bash
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --open
```

docs: show the required feature on docs.rs

---

src/trait_async.rs
src/trait_sync.rs

This was likely intended from the beginning and is the consistent usage pattern.
BREAKING CHANGE: all params are now by reference and are not moved anymore

perf!: always take params reference

---

src/response.rs
src/trait_async.rs
src/trait_sync.rs

This results in all methods returning a `MessageResponse<T>` which is more consistent. (and allows for #210)
BREAKING CHANGE: EditMessageResponse is gone

refactor!: use MessageOrBool over EditMessageResponse

---

Cargo.toml
src/lib.rs

As this causes confusion it will also be the default in the upcoming Rust edition 2024. See https://doc.rust-lang.org/nightly/edition-guide/rust-2024/cargo-remove-implicit-features.html
BREAKING CHANGE: Optional dependencies are no longer features. They were never intended to be used directly.

build!: remove implicit features

---

src/client_reqwest.rs
src/client_ureq.rs

Using the destructuring might mistakenly result in a wrong output. This could be misleading. For example an error code of 500 would result in the panic message while its still an API Error.
This moves the assertions to `assert_eq` and only destructures the `Error::Api`

test: improve testing for api error response

---

Cargo.toml
src/response.rs
src/trait_async.rs
src/trait_sync.rs

Utilise macros to do the repetitive stuff.
This automatically adds doc comments with a link to the Telegram API of the given method.
BREAKING CHANGE: `request_without_body` method is gone. This was meant to be used internally and probably not used elsewhere.
BREAKING CHANGE: `AsyncTelegramApi` requires `Sync`.
This was likely the case already via `#[async_trait]` but wasn't explicitly specified.

refactor!: simplify traits with macros

---

Cargo.toml
src/api_params.rs
src/lib.rs
src/macros.rs
src/objects.rs
src/response.rs

This combines all the serde and builder settings for the API structs into a single macro. [`serde_with::skip_serializing_none`](https://docs.rs/serde_with/3.9.0/serde_with/attr.skip_serializing_none.html) allows removing all the `#[serde(skip_serializing_if = "Option::is_none")]`.
Doing something similar for the enums results in more lines before, so I just cleaned them up to use the same order of derives.
Nothing of this PR should be breaking.

refactor: generalize serde logic into macro

---

.github/workflows/rust.yml
Cargo.toml
src/client_reqwest.rs
src/lib.rs
src/trait_async.rs

Add the wasm feature, ensuring it functions correctly with worker-rs.
Temporarily remove the logic related to request_with_form_data involving files; I will implement a replacement for this later.
Note that multipart may not function with the wasm feature; I will look for an alternative solution in the future.
#224

try fit wasm partially

---

src/objects.rs

https://core.telegram.org/bots/api#december-4-2024

Bot API 8.1

---

.github/workflows/rust.yml
Cargo.toml
README.md
src/lib.rs

This will definitely break for people as the default is gone and all features have different names. But I think the names are more helpful.

build!: rename the features and remove the default feature

---

Cargo.toml
src/client_reqwest.rs
src/client_ureq.rs
src/error.rs
src/json.rs
src/lib.rs
src/parse_mode.rs
src/test_json.rs

Bugfix: A failing file doesn't panic anymore with client-ureq.
BREAKING CHANGE: decode_response methods are now private. They probably shouldn't have been public in the first place
BREAKING CHANGE: mostly all Error variants are now different (only the Api error response is the same)

feat(error)!: more specific errors including their source

---

README.md
examples/api_trait_implementation.rs
examples/async_custom_client.rs
examples/async_file_upload.rs
examples/async_get_me.rs
examples/async_reply_to_message_updates.rs
examples/custom_client.rs
examples/get_me.rs
examples/inline_keyboard.rs
examples/reply_keyboard.rs
examples/reply_to_message_updates.rs
src/client_reqwest.rs
src/client_ureq.rs
src/lib.rs

With having both named `Api` and `TelegramApi` it's not as easy to understand what is what. One describes the interface (`TelegramApi`) and one is used to actually interact with the Bot (`Bot`).
As the update to 0.39 will require users to explicitly specify the new features they will know the name of the HTTP client they want anyway.

feat!: name clients Bot to differentiate from TelegramApi

---

src/trait_async.rs
src/trait_sync.rs

While #256 added the `FileUpload` for cover, it did not correctly handle the actual `FileUpload`. Which I also forgot :innocent:

fix: attach video cover correctly as a file

---

examples/api_trait_implementation.rs
examples/async_custom_client.rs
examples/async_file_upload.rs
examples/async_get_me.rs
examples/async_reply_to_message_updates.rs
examples/custom_client.rs
examples/get_me.rs
examples/inline_keyboard.rs
examples/reply_keyboard.rs
examples/reply_to_message_updates.rs

Specifying secrets (mainly the bot token) in code is not very smart and examples shouldn't encourage this.
Also, it's just simpler to run examples with specifying something once in the current shell and then run different examples without needing to change them first.

docs(examples): read token and chat from env

---

src/api_params.rs
src/client_ureq.rs
src/input_file.rs
src/lib.rs
src/macros.rs
src/objects.rs
src/trait_async.rs
src/trait_sync.rs

This trait works for both FileUpload and Option<FileUpload> which simplifies creating macros a lot.
The replace_attach method replaces an InputFile with an attach string in-place returning the previous InputFile without any clones. While this is neat it's not a big change for the PathBuf. When some code in the future involves Vec<u8> this will make a way bigger difference.
BREAKING CHANGE: method set_sticker_set_thumb is now named set_sticker_set_thumbnail like in the official API documentation.
BREAKING CHANGE: some imports are shifted around (api_params → input_file)

refactor!: simplify code with internal HasInputFile trait

---

examples/async_reply_to_message_updates.rs
examples/inline_keyboard.rs
examples/reply_keyboard.rs
examples/reply_to_message_updates.rs
src/api_params.rs
src/client_ureq.rs
src/games.rs
src/inline_mode.rs
src/input_media.rs
src/lib.rs
src/macros.rs
src/objects.rs
src/passport.rs
src/payments.rs
src/stickers.rs
src/trait_async.rs
src/trait_sync.rs
src/updates.rs

Also, add From implementations for some enums.
For categories in the Bot API documentation I did not provide top level re-exports. They are separated on the website so they can also be imported from their own module by users.
files except trait_*, api_params and objects should be sorted like they are on the Bot API Documentation Website.
BREAKING CHANGE: imports change
BREAKING CHANGE: Media renamed to MediaGroupInputMedia

refactor!: move objects into multiple modules

---

src/client_ureq.rs
src/objects.rs
src/response.rs

BREAKING CHANGE: ResponseParams moves to different module
BREAKING CHANGE: ResponseParams builder is gone. Its something that should only be read. Therefore, a bit less compile time.

refactor!: move ResponseParams to response module

---

src/objects.rs

It's simpler to write than `LinkPreviewOptions::builder().is_disabled(true).build()` all the time.

feat: add LinkPreviewOptions::DISABLED

---

.github/workflows/rust.yml

Running on beta mainly uses up a lot of resources without much benefit. Doing this on stable and the MSRV is way more useful in comparison. The main benefit of beta is to check that the beta channel works in order to provide feedback to Rust. Thats already done with test and clippy (and therefore check).

ci(rust): dont check features on beta

---

examples/async_reply_to_message_updates.rs
src/response.rs
src/types.rs
src/updates.rs

BREAKING CHANGE: messages might need to be unboxed before usage

refactor!: box large enum variants

---

src/types.rs

Fixes #285
Note that this is a breaking change for anyone using `year` field on `Birthdate`.

fix!: Optional `year`

---

src/payments.rs

Didn't work. Did as in the documentation.
doc - https://core.telegram.org/bots/api#startransaction

fix: Optional `nanostar_amount`

---

src/client_reqwest.rs
src/client_ureq.rs

Seeing the improved clippy::implicit_clone suggestions on nightly I found this case where serde_json::from_str basically creates owned values only to clone them direcly to create the multipart form.
As serde did not parsed into a map and rather a Value in between this required clones but merging this results in owned values.

perf(client): less clones on creating multipart form
