src/api_params.rs, src/objects.rs
Resolves https://github.com/ayrat555/frankenstein/issues/3
=> implement changes from Bot API 5.2

Cargo.toml, README.md, examples/api_trait_implementation.rs, examples/reply_to_message_updates.rs, src/api.rs, src/api_impl.rs, src/lib.rs
Allow to replace a default http client
=> create TelegramApi trait

.github/dependabot.yml, .github/workflows/rust.yml, .github/workflows/style.yml, examples/api_trait_implementation.rs, examples/reply_to_message_updates.rs, src/api_impl.rs, src/lib.rs
Also some lints are already handled:
- some lints are just done (mainly examples)
- some lints are allowed for now (in lib.rs)
=> Run CI in GitHub Actions

.github/workflows/rust.yml, src/api.rs, src/api_impl.rs, src/api_params.rs, src/objects.rs
resolves https://github.com/ayrat555/frankenstein/issues/17
=> Telegram API 5.3 changes

src/objects.rs
=> fix ReplyKeyboardMarkup serialization error

src/api_impl.rs, src/api_params.rs
=> Make SendChatActionParams.action an enum

.github/workflows/rust.yml, examples/api_trait_implementation.rs, src/api_impl.rs, src/lib.rs
Add improvements from https://github.com/EdJoPaTo/rust-binary-metafile-template
This tests multiple different feature sets now.
- `--no-default-features` fails currently without the fixes from #30 (I can rebase once its merged)
- `--all-features` and the default features are equivalent currently
Also creation of docs is checked.
Additionally some more lints are ignored and some lint hints are applied.
=> improve ci and ignore some lints

Cargo.toml, examples/api_trait_implementation.rs, examples/reply_to_message_updates.rs, src/api.rs, src/api_impl.rs, src/api_params.rs, src/objects.rs
resolves https://github.com/ayrat555/frankenstein/pull/34
=> use builder derive

CHANGELOG.md, Cargo.toml, README.md, src/api_impl.rs, src/api_params.rs, src/objects.rs
- Added the field is_video to the classes Sticker and StickerSet.
- Added the parameter webm_sticker to the methods createNewStickerSet and addStickerToSet.
=> Bot API 5.7

.github/dependabot.yml, .github/workflows/rust.yml, .github/workflows/style.yml
get the improvements from
https://github.com/EdJoPaTo/rust-binary-metafile-template
=> improve ci

.github/workflows/rust.yml, Cargo.toml, examples/inline_keyboard.rs, examples/reply_keyboard.rs
closes https://github.com/ayrat555/frankenstein/issues/55
=> add keyboard examples

README.md, examples/async_reply_to_message_updates.rs, examples/reply_to_message_updates.rs, src/api/telegram_api_impl.rs, src/api_params.rs, src/objects.rs
instead of having string values, use json to generate strings from a fixed set of enum values
=> make allowed_update type safe

src/objects.rs
=> change type of file_size from u32 to u64

README.md, examples/api_trait_implementation.rs, src/api.rs, src/api_params.rs, src/api_traits.rs, src/objects.rs
See https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
Also simplify example/readme
=> refactor: specify Eq when possible on PartialEq

src/objects.rs
Use 'kicked' status according to https://core.telegram.org/bots/api/#chatmemberbanned
=> Fix status for ChatMemberBanned

README.md
=> Bots created with frankenstein

src/api/async_telegram_api_impl.rs
https://github.com/ayrat555/frankenstein/pull/82/files#r926292324
=> change connect_timeout for async client

src/api_params.rs
fixes https://github.com/ayrat555/frankenstein/issues/84
=> change the offset field's type for getUpdates

CHANGELOG.md, Cargo.toml, README.md, src/api/telegram_api_impl.rs, src/api_params.rs, src/objects.rs
https://core.telegram.org/bots/api#february-3-2023
=> Bop API 6.5 Changes

src/api_params.rs, src/api_traits/async_telegram_api.rs, src/api_traits/telegram_api.rs, src/objects.rs
https://core.telegram.org/bots/api#april-21-2023
=> Bot API 6.7 changes

src/api_params.rs, src/api_traits/async_telegram_api.rs, src/api_traits/telegram_api.rs, src/objects.rs
[Bot api 6.8](https://core.telegram.org/bots/api#august-18-2023)
=> Bot api 6.8 

Cargo.toml, src/api_params.rs, src/objects.rs
https://core.telegram.org/bots/api#september-22-2023
=> Bot API 6.9

src/api_traits/async_telegram_api.rs, src/api_traits/telegram_api.rs
fixes https://github.com/ayrat555/frankenstein/issues/121
=> add `unpin_all_chat_messages` method

src/objects.rs
fixes https://github.com/ayrat555/frankenstein/issues/142
thank you @intersparkle
=> fix custom emoji decoding

src/api/telegram_api_impl.rs, src/api_params.rs, src/api_traits/async_telegram_api.rs, src/api_traits/telegram_api.rs, src/objects.rs
https://core.telegram.org/bots/api#may-6-2024
=> Bot API 7.3 

.github/workflows/rust.yml, Cargo.toml, src/lib.rs
See the individual commits for a description of what I improved here.
As with the last times I got the improvements from my personal template https://github.com/EdJoPaTo/rust-binary-metafile-template
=> build: configure lints in Cargo.toml and improve CI

src/api_params.rs, src/api_traits/async_telegram_api.rs, src/api_traits/telegram_api.rs, src/objects.rs
https://core.telegram.org/bots/api#june-18-2024
=> Bot API 7.5

src/objects.rs
https://core.telegram.org/bots/api#update
=> fix: `ChatBoostUpdated` in `UpdateContent`

src/api/telegram_api_impl.rs
=> refactor: simplify From<ureq::Error>

Cargo.toml, src/lib.rs
=> build(cargo): enable nursery lints

src/client_reqwest.rs, src/client_ureq.rs
Basically moves the file_name logic into the loop which handles everything else.
=> refactor: simplify file handling loop

src/stickers.rs
=> fix(gift): fix typo in property name

src/gifts.rs, src/methods.rs, src/trait_async.rs, src/trait_sync.rs, src/types.rs
https://core.telegram.org/bots/api#july-3-2025
=> feat: Bot API 9.1
